version: "2"
# ci concept test
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8089:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
  tomcat:
    image: tomcat:8.0
    ports:
      - "8087:8080"